# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64, ci-linux-01]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install node modules
      - name: Install node modules
        # working-directory: frontend
        run: |
          yarn install

      # Build Package
      - name: Build package
        # working-directory: frontend
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          yarn build

      # Commit Package
      - name: Commit report
        run: |
          git config --global user.name 'Mattia-gh-action'
          git config --global user.email 'ronzim@users.noreply.github.com'
          git commit -am "Automated package build"
          git push
      # Generate docs
      # - name: Generate docs
      #   run: |
      #     yarn generate-docs
